# Generated by Django 6.0.7 on 2026-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lalafo_app1', '0002_category_category_image_product_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Bishkek', max_length=30),
            preserve_default=False,
        ),
    ]
