# Generated by Django 6.0.7 on 2026-07-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lalafo_app1', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.BooleanField(default=False),
        ),
    ]
